spring:
  freemarker:
    expose-request-attributes: true
  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: vivi
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog-master.yml

